@echo off
REM ######################################
REM NE301 Toolchain Setup Script for Windows
REM ######################################

setlocal enabledelayedexpansion

echo =========================================
echo NE301 Toolchain Setup for Windows
echo =========================================
echo.

REM Check if ARM GCC is installed
where arm-none-eabi-gcc >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] ARM GCC toolchain found
    arm-none-eabi-gcc --version | findstr /C:"arm-none-eabi-gcc"
    goto :check_deps
)

echo [!] ARM GCC toolchain not found
echo.
echo Please install one of the following:
echo.
echo 1. STM32CubeCLT ^(Recommended^)
echo    Download: https://www.st.com/stm32cubeclt
echo    Install to: C:\ST\STM32CubeCLT
echo.
echo 2. ARM GNU Toolchain
echo    Download: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads
echo    Select: arm-gnu-toolchain-*-mingw-w64-i686-arm-none-eabi.exe
echo.

set /p INSTALL_PATH="Enter toolchain bin path (or press Enter to exit): "
if "%INSTALL_PATH%"=="" (
    echo Installation cancelled
    exit /b 1
)

REM Add to PATH for current session
set PATH=%INSTALL_PATH%;%PATH%

REM Verify installation
where arm-none-eabi-gcc >nul 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo [ERROR] Toolchain still not found. Please check the path.
    exit /b 1
)

:check_deps
echo.
echo Checking essential dependencies...

REM Check make
where make >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] Make found
) else (
    echo [!] Make not found
    echo     Install Git for Windows: https://git-scm.com/
)

REM Check Python
where python >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] Python found
    python --version
) else (
    echo [!] Python not found
    echo     Install from: https://www.python.org/
)

REM Check Node.js
where node >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] Node.js found
    node --version
) else (
    echo [!] Node.js not found
    echo     Install from: https://nodejs.org/
)

REM Check pnpm
where pnpm >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] pnpm found
) else (
    echo [!] pnpm not found
    echo     Installing pnpm...
    npm install -g pnpm
)

echo.
echo Checking optional tools...

REM Check STM32 Programmer
where STM32_Programmer_CLI >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] STM32_Programmer_CLI found
) else (
    echo [!] STM32_Programmer_CLI not found ^(optional^)
    echo     Download: https://www.st.com/stm32cubeprog
)

REM Check STM32 Signing Tool
where STM32_SigningTool_CLI >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] STM32_SigningTool_CLI found
) else (
    echo [!] STM32_SigningTool_CLI not found ^(optional^)
    echo     Included in STM32CubeCLT
)

REM Check stedgeai
where stedgeai >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] stedgeai found
) else (
    echo [!] stedgeai not found ^(optional, for AI model generation^)
    echo     Download: https://www.st.com/en/development-tools/stedgeai-core.html#get-software
)

REM Check STEDGEAI_CORE_DIR
if defined STEDGEAI_CORE_DIR (
    echo [OK] STEDGEAI_CORE_DIR = %STEDGEAI_CORE_DIR%
) else (
    echo [!] STEDGEAI_CORE_DIR not set ^(optional^)
)

REM Generate configuration file
echo.
echo Generating configuration file...

REM Get toolchain path
for /f "delims=" %%i in ('where arm-none-eabi-gcc 2^>nul') do set TOOLCHAIN_BIN=%%i
for %%i in ("%TOOLCHAIN_BIN%") do set TOOLCHAIN_DIR=%%~dpi

echo # NE301 Makefile Configuration > .make.env
echo # Auto-generated by setup script >> .make.env
echo. >> .make.env
echo # ARM GCC Toolchain path >> .make.env
echo GCC_PATH = %TOOLCHAIN_DIR% >> .make.env
echo. >> .make.env
echo # Parallel build jobs >> .make.env
echo # MAKEFLAGS += -j$(NUMBER_OF_PROCESSORS) >> .make.env
echo. >> .make.env
echo # Flash addresses ^(can be customized^) >> .make.env
echo # FLASH_ADDR_FSBL = 0x34000000 >> .make.env
echo # FLASH_ADDR_APP = 0x70100000 >> .make.env
echo # FLASH_ADDR_WEB = 0x90400000 >> .make.env
echo # FLASH_ADDR_MODEL = 0x90700000 >> .make.env
echo. >> .make.env
echo # ST Edge AI Core ^(for AI model generation^) >> .make.env
echo # Uncomment and set if you have ST Edge AI installed: >> .make.env
echo # export STEDGEAI_CORE_DIR=C:\path\to\STEdgeAI >> .make.env

echo [OK] Configuration saved to .make.env

REM Test build system
echo.
echo Testing build system...
make info >nul 2>&1
if %ERRORLEVEL% == 0 (
    echo [OK] Build system test passed
    make info
) else (
    echo [!] Build system test failed
    echo     Check if make and toolchain are properly configured
)

echo.
echo =========================================
echo Setup Complete!
echo =========================================
echo.
echo Essential tools installed:
echo   [OK] ARM GCC Compiler
echo   [OK] Make
echo   [OK] Python
echo   [OK] Node.js ^& pnpm
echo.

REM Check if optional tools are available
set HAS_FLASH=0
set HAS_AI=0

where STM32_Programmer_CLI >nul 2>&1
if %ERRORLEVEL% == 0 set HAS_FLASH=1

where stedgeai >nul 2>&1
if %ERRORLEVEL% == 0 (
    if defined STEDGEAI_CORE_DIR set HAS_AI=1
)

if %HAS_FLASH% == 0 (
    echo Optional tools ^(install separately^):
)
if %HAS_FLASH% == 0 (
    echo   [!] STM32CubeProgrammer - for flashing firmware
    echo     Download: https://www.st.com/stm32cubeprog
)
if %HAS_AI% == 0 (
    echo   [!] ST Edge AI ^(stedgeai^) - for AI model generation
    echo     Download: https://www.st.com/en/development-tools/stedgeai-core.html#get-software
    echo     Set STEDGEAI_CORE_DIR environment variable after install
)
if %HAS_FLASH% == 0 echo.

echo Next steps:
echo   1. make              # Build firmware
echo   2. make web          # Build web frontend
if %HAS_AI% == 1 (
    echo   3. make model        # Build AI model
    echo   4. make flash        # Flash all to device
) else if %HAS_FLASH% == 1 (
    echo   3. make flash        # Flash to device
)
echo.
echo For help: make help
echo To verify: check_env.bat
echo =========================================
echo.

pause

